name: Release

on:
    push:
        tags:
          - 'v*'
jobs:
    build-deb:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Configure
              run: cmake -S . -B build -DCPACK_GENERATOR=DEB
            - name: Build
              run: cmake --build build

            - name : Pack
              run: cd build && cpack

            - name: Upload deb
              uses: actions/upload-artifact@v4
              with:
                name: deb-pkg
                path: build/*.deb



    build-rpm:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Install RMP dependencies
              run: sudo apt-get install -y rpm

            - name: Configure
              run: cmake -S . -B build -DCPACK_GENERATOR=RPM
            - name: Build
              run: cmake --build build

            - name : Pack
              run: cd build && cpack

            - name: Upload rpm
              uses: actions/upload-artifact@v4
              with:
                name: rpm-pkg
                path: build/*.rpm


    build-dmg:
        runs-on: macos-latest
        steps:
            - uses: actions/checkout@v4

            - name: Configure
              run: cmake -S . -B build -DCPACK_GENERATOR=DragNDrop
            - name: Build
              run: cmake --build build

            - name : Pack
              run: cd build && cpack

            - name: Upload dmg
              uses: actions/upload-artifact@v4
              with:
                name: dmg-pkg
                path: build/*.dmg

    build-msi:
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v4

            - name: Configure
              run: cmake -S . -B build -DCPACK_GENERATOR=WIX
            - name: Build
              run: cmake --build build --config Release

            - name : Pack
              run: cd build && cpack

            - name: Upload msi
              uses: actions/upload-artifact@v4
              with:
                name: msi-pkg
                path: build/*.msi

    release:
        needs: [build-deb, build-rpm, build-dmg, build-msi]
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - uses: actions/download-artifact@v4
              with:
                path: packages

            - uses: softprops/action-gh-release@v2
              with:
                files: packages/**/*
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
